[package]
name = "julia_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Critical for Julia FFI - produces C dynamic library

[dependencies]
# No flutter_rust_bridge dependency - this is pure C FFI